baseURL = 'https://zuoshiyue.github.io/hugo-page-v1/'
languageCode = 'en-us'
title = 'zuoshiyue Site'

theme = 'LoveIt'

# 菜单配置
  [menu]
    [[menu.main]]
      weight = 1
      identifier = "posts"
      # 你可以在名称 (允许 HTML 格式) 之前添加其他信息, 例如图标
      pre = ""
      # 你可以在名称 (允许 HTML 格式) 之后添加其他信息, 例如图标
      post = ""
      name = "文章"
      url = "/posts/"
      # 当你将鼠标悬停在此菜单链接上时, 将显示的标题
      title = ""
    [[menu.main]]
      weight = 2
      identifier = "tags"
      pre = ""
      post = ""
      name = "标签"
      url = "/tags/"
      title = ""